-- ============================================================
--  Restore: CRISTIAN JOSH Q. MAYO attendance logs only
--  Source: OJT_Report_all.xlsx (full import document)
--  Total: 14 days, 27 log entries
-- ============================================================

INSERT INTO attendance_logs (student_id, student_name, status, task_accomplishment, is_overtime, timestamp) SELECT id, 'CRISTIAN JOSH Q. MAYO', 'Time In', 'Ongoing...', 0, '2026-03-10 07:38:00' FROM students WHERE full_name = 'CRISTIAN JOSH Q. MAYO' LIMIT 1;
INSERT INTO attendance_logs (student_id, student_name, status, task_accomplishment, is_overtime, timestamp) SELECT id, 'CRISTIAN JOSH Q. MAYO', 'Time In', 'Ongoing...', 0, '2026-03-09 07:35:00' FROM students WHERE full_name = 'CRISTIAN JOSH Q. MAYO' LIMIT 1;
INSERT INTO attendance_logs (student_id, student_name, status, task_accomplishment, is_overtime, timestamp) SELECT id, 'CRISTIAN JOSH Q. MAYO', 'Time Out', 'Added feature in service table', 0, '2026-03-09 17:00:00' FROM students WHERE full_name = 'CRISTIAN JOSH Q. MAYO' LIMIT 1;
INSERT INTO attendance_logs (student_id, student_name, status, task_accomplishment, is_overtime, timestamp) SELECT id, 'CRISTIAN JOSH Q. MAYO', 'Time In', 'Ongoing...', 0, '2026-03-05 07:47:00' FROM students WHERE full_name = 'CRISTIAN JOSH Q. MAYO' LIMIT 1;
INSERT INTO attendance_logs (student_id, student_name, status, task_accomplishment, is_overtime, timestamp) SELECT id, 'CRISTIAN JOSH Q. MAYO', 'Time Out', 'Debugging', 0, '2026-03-05 17:00:00' FROM students WHERE full_name = 'CRISTIAN JOSH Q. MAYO' LIMIT 1;
INSERT INTO attendance_logs (student_id, student_name, status, task_accomplishment, is_overtime, timestamp) SELECT id, 'CRISTIAN JOSH Q. MAYO', 'Time In', 'Ongoing...', 0, '2026-03-04 07:47:00' FROM students WHERE full_name = 'CRISTIAN JOSH Q. MAYO' LIMIT 1;
INSERT INTO attendance_logs (student_id, student_name, status, task_accomplishment, is_overtime, timestamp) SELECT id, 'CRISTIAN JOSH Q. MAYO', 'Time Out', 'Front desk, fix the website/ debugging', 0, '2026-03-04 17:00:00' FROM students WHERE full_name = 'CRISTIAN JOSH Q. MAYO' LIMIT 1;
INSERT INTO attendance_logs (student_id, student_name, status, task_accomplishment, is_overtime, timestamp) SELECT id, 'CRISTIAN JOSH Q. MAYO', 'Time In', 'Ongoing...', 0, '2026-03-03 07:47:00' FROM students WHERE full_name = 'CRISTIAN JOSH Q. MAYO' LIMIT 1;
INSERT INTO attendance_logs (student_id, student_name, status, task_accomplishment, is_overtime, timestamp) SELECT id, 'CRISTIAN JOSH Q. MAYO', 'Time Out', 'Front desk, data encoding, make roa', 0, '2026-03-03 17:01:00' FROM students WHERE full_name = 'CRISTIAN JOSH Q. MAYO' LIMIT 1;
INSERT INTO attendance_logs (student_id, student_name, status, task_accomplishment, is_overtime, timestamp) SELECT id, 'CRISTIAN JOSH Q. MAYO', 'Time In', 'Ongoing...', 0, '2026-03-02 08:00:00' FROM students WHERE full_name = 'CRISTIAN JOSH Q. MAYO' LIMIT 1;
INSERT INTO attendance_logs (student_id, student_name, status, task_accomplishment, is_overtime, timestamp) SELECT id, 'CRISTIAN JOSH Q. MAYO', 'Time Out', 'Front desk, utm, data encoding', 0, '2026-03-02 16:59:00' FROM students WHERE full_name = 'CRISTIAN JOSH Q. MAYO' LIMIT 1;
INSERT INTO attendance_logs (student_id, student_name, status, task_accomplishment, is_overtime, timestamp) SELECT id, 'CRISTIAN JOSH Q. MAYO', 'Time In', 'Ongoing...', 0, '2026-02-26 07:49:00' FROM students WHERE full_name = 'CRISTIAN JOSH Q. MAYO' LIMIT 1;
INSERT INTO attendance_logs (student_id, student_name, status, task_accomplishment, is_overtime, timestamp) SELECT id, 'CRISTIAN JOSH Q. MAYO', 'Time Out', 'Debugging, encoding', 0, '2026-02-26 17:00:00' FROM students WHERE full_name = 'CRISTIAN JOSH Q. MAYO' LIMIT 1;
INSERT INTO attendance_logs (student_id, student_name, status, task_accomplishment, is_overtime, timestamp) SELECT id, 'CRISTIAN JOSH Q. MAYO', 'Time In', 'Ongoing...', 0, '2026-02-25 07:43:00' FROM students WHERE full_name = 'CRISTIAN JOSH Q. MAYO' LIMIT 1;
INSERT INTO attendance_logs (student_id, student_name, status, task_accomplishment, is_overtime, timestamp) SELECT id, 'CRISTIAN JOSH Q. MAYO', 'Time Out', 'Encoding of database and debugging', 0, '2026-02-25 17:00:00' FROM students WHERE full_name = 'CRISTIAN JOSH Q. MAYO' LIMIT 1;
INSERT INTO attendance_logs (student_id, student_name, status, task_accomplishment, is_overtime, timestamp) SELECT id, 'CRISTIAN JOSH Q. MAYO', 'Time In', 'Ongoing...', 0, '2026-02-24 07:53:00' FROM students WHERE full_name = 'CRISTIAN JOSH Q. MAYO' LIMIT 1;
INSERT INTO attendance_logs (student_id, student_name, status, task_accomplishment, is_overtime, timestamp) SELECT id, 'CRISTIAN JOSH Q. MAYO', 'Time Out', 'fix servicetable, tallymodal and editclient, connected the new table in database to backend', 0, '2026-02-24 17:02:00' FROM students WHERE full_name = 'CRISTIAN JOSH Q. MAYO' LIMIT 1;
INSERT INTO attendance_logs (student_id, student_name, status, task_accomplishment, is_overtime, timestamp) SELECT id, 'CRISTIAN JOSH Q. MAYO', 'Time In', 'Ongoing...', 0, '2026-02-23 07:44:00' FROM students WHERE full_name = 'CRISTIAN JOSH Q. MAYO' LIMIT 1;
INSERT INTO attendance_logs (student_id, student_name, status, task_accomplishment, is_overtime, timestamp) SELECT id, 'CRISTIAN JOSH Q. MAYO', 'Time Out', 'Fix add client and database logic', 0, '2026-02-23 16:58:00' FROM students WHERE full_name = 'CRISTIAN JOSH Q. MAYO' LIMIT 1;
INSERT INTO attendance_logs (student_id, student_name, status, task_accomplishment, is_overtime, timestamp) SELECT id, 'CRISTIAN JOSH Q. MAYO', 'Time In', 'Ongoing...', 0, '2026-02-19 07:46:00' FROM students WHERE full_name = 'CRISTIAN JOSH Q. MAYO' LIMIT 1;
INSERT INTO attendance_logs (student_id, student_name, status, task_accomplishment, is_overtime, timestamp) SELECT id, 'CRISTIAN JOSH Q. MAYO', 'Time Out', 'Fix tally modal table, encoding of data', 0, '2026-02-19 17:00:00' FROM students WHERE full_name = 'CRISTIAN JOSH Q. MAYO' LIMIT 1;
INSERT INTO attendance_logs (student_id, student_name, status, task_accomplishment, is_overtime, timestamp) SELECT id, 'CRISTIAN JOSH Q. MAYO', 'Time In', 'Ongoing...', 0, '2026-02-18 07:54:00' FROM students WHERE full_name = 'CRISTIAN JOSH Q. MAYO' LIMIT 1;
INSERT INTO attendance_logs (student_id, student_name, status, task_accomplishment, is_overtime, timestamp) SELECT id, 'CRISTIAN JOSH Q. MAYO', 'Time Out', 'Front desk', 0, '2026-02-18 16:56:00' FROM students WHERE full_name = 'CRISTIAN JOSH Q. MAYO' LIMIT 1;
INSERT INTO attendance_logs (student_id, student_name, status, task_accomplishment, is_overtime, timestamp) SELECT id, 'CRISTIAN JOSH Q. MAYO', 'Time In', 'Ongoing...', 0, '2026-02-16 07:41:00' FROM students WHERE full_name = 'CRISTIAN JOSH Q. MAYO' LIMIT 1;
INSERT INTO attendance_logs (student_id, student_name, status, task_accomplishment, is_overtime, timestamp) SELECT id, 'CRISTIAN JOSH Q. MAYO', 'Time Out', 'Fix bug in addclient/editclient front end and server backend', 0, '2026-02-16 17:02:00' FROM students WHERE full_name = 'CRISTIAN JOSH Q. MAYO' LIMIT 1;
INSERT INTO attendance_logs (student_id, student_name, status, task_accomplishment, is_overtime, timestamp) SELECT id, 'CRISTIAN JOSH Q. MAYO', 'Time In', 'Ongoing...', 0, '2026-02-12 08:01:00' FROM students WHERE full_name = 'CRISTIAN JOSH Q. MAYO' LIMIT 1;
INSERT INTO attendance_logs (student_id, student_name, status, task_accomplishment, is_overtime, timestamp) SELECT id, 'CRISTIAN JOSH Q. MAYO', 'Time Out', 'Fix the logic in service table', 0, '2026-02-12 16:39:00' FROM students WHERE full_name = 'CRISTIAN JOSH Q. MAYO' LIMIT 1;

-- Done: 27 entries restored for CRISTIAN JOSH Q. MAYO (14 days)
